services:
  db:
    image: postgres:16
    container_name: investimentos_db
    environment:
      POSTGRES_DB: investimentos
      POSTGRES_USER: invest_user
      POSTGRES_PASSWORD: invest_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pipeline:
    build: .
    container_name: investimentos_pipeline
    depends_on:
      - db
    env_file:
      - scripts/.env
    volumes:
      #- logs_volume:/app/logs      Antes os volumes estava configurados assim por problema no Mount. fikeWatcherType parece que resolveu 100%
      #- data_volume:/data          Vou monitorar, depois apago essas linhas
      - ./data:/app/data
      - ./logs:/app/logs
    command: python scripts/roteiro_central.py

  dashboard:
    build: .
    container_name: investimentos-dashboard
    ports:
      - "8501:8501"
    env_file:
      - scripts/.env
    depends_on:
      - db
    volumes:
      #- logs_volume:/app/logs       Antes os volumes estava configurados assim por problema no Mount. fikeWatcherType parece que resolveu 100%
      #- data_volume:/data           Vou monitorar, depois apago essas linhas
      - ./data:/app/data
      - ./logs:/app/logs
    command: streamlit run dashboard/app.py --server.fileWatcherType none

volumes:
  pgdata:
  #data_volume:
  #logs_volume: